
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMENT SYNTAX_BRACE MACRO PH_6 PH_5 PH_4 PH_3 PH_2 PH_1 P_6 P_5 P_4 P_3 P_2 P_1 TEXT_BOLD_ITALIC TEXT_BOLD TEXT_ITALIC TEXT_CANCEL1 TEXT_CANCEL2 TEXT_UNDERLINE TEXT_UPPER TEXT_LOWER TABLE NAME NUMBERwikidoc  : wikidoc expression\n                | expressionexpression : paragraph\n                  | SYNTAX_BRACEparagraph  : PH_6\n                  | PH_5\n                  | PH_4\n                  | PH_3\n                  | PH_2\n                  | PH_1\n                  | P_6\n                  | P_5\n                  | P_4\n                  | P_3\n                  | P_2\n                  | P_1'
    
_lr_action_items = {'SYNTAX_BRACE':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,],[4,4,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-14,-15,-16,-1,]),'PH_6':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,],[5,5,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-14,-15,-16,-1,]),'PH_5':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,],[6,6,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-14,-15,-16,-1,]),'PH_4':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,],[7,7,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-14,-15,-16,-1,]),'PH_3':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,],[8,8,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-14,-15,-16,-1,]),'PH_2':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,],[9,9,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-14,-15,-16,-1,]),'PH_1':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,],[10,10,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-14,-15,-16,-1,]),'P_6':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,],[11,11,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-14,-15,-16,-1,]),'P_5':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,],[12,12,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-14,-15,-16,-1,]),'P_4':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,],[13,13,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-14,-15,-16,-1,]),'P_3':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,],[14,14,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-14,-15,-16,-1,]),'P_2':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,],[15,15,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-14,-15,-16,-1,]),'P_1':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,],[16,16,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-14,-15,-16,-1,]),'$end':([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,],[0,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-14,-15,-16,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'wikidoc':([0,],[1,]),'expression':([0,1,],[2,17,]),'paragraph':([0,1,],[3,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> wikidoc","S'",1,None,None,None),
  ('wikidoc -> wikidoc expression','wikidoc',2,'p_wikidoc','parsing_kiwi.py',209),
  ('wikidoc -> expression','wikidoc',1,'p_wikidoc','parsing_kiwi.py',210),
  ('expression -> paragraph','expression',1,'p_expression','parsing_kiwi.py',213),
  ('expression -> SYNTAX_BRACE','expression',1,'p_expression','parsing_kiwi.py',214),
  ('paragraph -> PH_6','paragraph',1,'p_paragraph','parsing_kiwi.py',221),
  ('paragraph -> PH_5','paragraph',1,'p_paragraph','parsing_kiwi.py',222),
  ('paragraph -> PH_4','paragraph',1,'p_paragraph','parsing_kiwi.py',223),
  ('paragraph -> PH_3','paragraph',1,'p_paragraph','parsing_kiwi.py',224),
  ('paragraph -> PH_2','paragraph',1,'p_paragraph','parsing_kiwi.py',225),
  ('paragraph -> PH_1','paragraph',1,'p_paragraph','parsing_kiwi.py',226),
  ('paragraph -> P_6','paragraph',1,'p_paragraph','parsing_kiwi.py',227),
  ('paragraph -> P_5','paragraph',1,'p_paragraph','parsing_kiwi.py',228),
  ('paragraph -> P_4','paragraph',1,'p_paragraph','parsing_kiwi.py',229),
  ('paragraph -> P_3','paragraph',1,'p_paragraph','parsing_kiwi.py',230),
  ('paragraph -> P_2','paragraph',1,'p_paragraph','parsing_kiwi.py',231),
  ('paragraph -> P_1','paragraph',1,'p_paragraph','parsing_kiwi.py',232),
]
